# Rule Providers for this version (versioned_rules/2025-09-23)
# Generated at: 2025-09-23 02:10:56 UTC
rule-providers:
  # 原始名称: 👨‍💻 GitHub
  GitHub:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/GitHub.mrs"
    path: "./rules/GitHub.mrs"
    interval: 86400

  # 原始名称: 🎯 国内流量
  SteamCN:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/SteamCN.mrs"
    path: "./rules/SteamCN.mrs"
    interval: 86400

  # 原始名称: 🧚 AI
  AI:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/AI.mrs"
    path: "./rules/AI.mrs"
    interval: 86400

  # 原始名称: 🧚 AI
  AI:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/AI.mrs"
    path: "./rules/AI.mrs"
    interval: 86400

  # 原始名称: 🧚 AI
  AI:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/AI.mrs"
    path: "./rules/AI.mrs"
    interval: 86400

  # 原始名称: 🧚 AI
  AI:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/AI.mrs"
    path: "./rules/AI.mrs"
    interval: 86400

  # 原始名称: 🧚 AI
  AI:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/AI.mrs"
    path: "./rules/AI.mrs"
    interval: 86400

  # 原始名称: 🧚 AI
  AI:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/AI.mrs"
    path: "./rules/AI.mrs"
    interval: 86400

  # 原始名称: 🎯 国内流量
  Lan:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/Lan.mrs"
    path: "./rules/Lan.mrs"
    interval: 86400

  # 原始名称: 🎯 国内流量
  UnBan:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/UnBan.mrs"
    path: "./rules/UnBan.mrs"
    interval: 86400

  # 原始名称: 🚀 国外流量
  PikPak:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/PikPak.mrs"
    path: "./rules/PikPak.mrs"
    interval: 86400

  # 原始名称: 🛸 IP归属地伪装
  IP:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/IP.mrs"
    path: "./rules/IP.mrs"
    interval: 86400

  # 原始名称: 🛑 广告拦截
  BanAD:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/BanAD.mrs"
    path: "./rules/BanAD.mrs"
    interval: 86400

  # 原始名称: 🛑 广告拦截
  ZhihuAds:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/ZhihuAds.mrs"
    path: "./rules/ZhihuAds.mrs"
    interval: 86400

  # 原始名称: 📹 YouTube
  YouTube:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/YouTube.mrs"
    path: "./rules/YouTube.mrs"
    interval: 86400

  # 原始名称: 🎥 Netflix
  Netflix:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/Netflix.mrs"
    path: "./rules/Netflix.mrs"
    interval: 86400

  # 原始名称: 🐹 DisneyPlus
  DisneyPlus:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/DisneyPlus.mrs"
    path: "./rules/DisneyPlus.mrs"
    interval: 86400

  # 原始名称: 📽️ PrimeVideo
  PrimeVideo:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/PrimeVideo.mrs"
    path: "./rules/PrimeVideo.mrs"
    interval: 86400

  # 原始名称: 🎦 HBO
  HBO:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/HBO.mrs"
    path: "./rules/HBO.mrs"
    interval: 86400

  # 原始名称: 🎦 HBO
  HBO:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/HBO.mrs"
    path: "./rules/HBO.mrs"
    interval: 86400

  # 原始名称: 🎦 HBO
  HBO:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/HBO.mrs"
    path: "./rules/HBO.mrs"
    interval: 86400

  # 原始名称: 🍎 AppleTV
  AppleTV:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/AppleTV.mrs"
    path: "./rules/AppleTV.mrs"
    interval: 86400

  # 原始名称: 🎬 EMBY
  EMBY:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/EMBY.mrs"
    path: "./rules/EMBY.mrs"
    interval: 86400

  # 原始名称: 🎬 EMBY
  EMBY:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/EMBY.mrs"
    path: "./rules/EMBY.mrs"
    interval: 86400

  # 原始名称: 📺 巴哈姆特
  Bahamut:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/Bahamut.mrs"
    path: "./rules/Bahamut.mrs"
    interval: 86400

  # 原始名称: 📺 Bilibili
  Bilibili:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/Bilibili.mrs"
    path: "./rules/Bilibili.mrs"
    interval: 86400

  # 原始名称: 🎵 Spotify
  Spotify:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/Spotify.mrs"
    path: "./rules/Spotify.mrs"
    interval: 86400

  # 原始名称: 🎶 TikTok
  TikTok:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/TikTok.mrs"
    path: "./rules/TikTok.mrs"
    interval: 86400

  # 原始名称: 🌍 国外媒体
  GlobalMedia_Classical:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/GlobalMedia_Classical.mrs"
    path: "./rules/GlobalMedia_Classical.mrs"
    interval: 86400

  # 原始名称: 🌏 国内媒体
  ChinaMedia:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/ChinaMedia.mrs"
    path: "./rules/ChinaMedia.mrs"
    interval: 86400

  # 原始名称: 🎯 国内流量
  GoogleCN:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/GoogleCN.mrs"
    path: "./rules/GoogleCN.mrs"
    interval: 86400

  # 原始名称: Ⓜ️ 微软云盘
  OneDrive:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/OneDrive.mrs"
    path: "./rules/OneDrive.mrs"
    interval: 86400

  # 原始名称: Ⓜ️ 微软服务
  Microsoft:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/Microsoft.mrs"
    path: "./rules/Microsoft.mrs"
    interval: 86400

  # 原始名称: 🍎 苹果服务
  Apple:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/Apple.mrs"
    path: "./rules/Apple.mrs"
    interval: 86400

  # 原始名称: 📲 Telegram
  Telegram:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/Telegram.mrs"
    path: "./rules/Telegram.mrs"
    interval: 86400

  # 原始名称: 🤖 Discord
  Discord:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/Discord.mrs"
    path: "./rules/Discord.mrs"
    interval: 86400

  # 原始名称: 🎮 游戏平台
  Game:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/Game.mrs"
    path: "./rules/Game.mrs"
    interval: 86400

  # 原始名称: 🎯 国内流量
  Download:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23/rules/Download.mrs"
    path: "./rules/Download.mrs"
    interval: 86400

